version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
       - 5672:5672
       - 15672:15672
  features:
    build:
      context: ./features
    restart: always
    depends_on:
      - rabbitmq
  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - rabbitmq
      - features
  metric:
    build:
      context: ./metrics
    volumes:
      - ./logs:/app/logs  # Связываем локальную директорию с директорией в контейнере
    restart: always
    depends_on:
      - rabbitmq
      - features
      - model
  plot:
    build:
      context: ./plot
    depends_on:
      - features
      - model
    volumes:
      - ./logs:/app/logs  # Связываем локальную директорию с директорией в контейнере







